import { lsGet, lsSet, lsDel } from "./storage.js";
import { markCut } from "./cut-text.js";
import { $ } from "./dom.js";

/* ---- UI LANGUAGE ------------------------------------------------------------------------
   The CHROME's language, not the CONTENT's: the EN|PL switch decides what is copied to
   the passenger, this decides what the buttons say - deliberately independent, since
   tying them would break the per-tab content switch.
   ONE RULE MAKES THE REST POSSIBLE: a missing key falls back to English - never blank,
   never the key name - so a half-translated build is honest rather than broken. Do not
   "fix" a missing string by inventing Polish here; leave it and it reads English.
   Impersonal register on purpose ("Zapisano", never "Zapisalem") - the -lem/-lam problem
   stays confined to catalog macros, where the author's own voice belongs. PAX, INTENT,
   ROLE, AGENT stay untranslated (desk jargon), and so does the Maintenance panel (a
   rescue room, not a settings room). */
/* A REGISTRY, not a pair - more languages are expected, so nothing may care how many
   there are. Adding one = one object + one UI_LANGS row; every lookup goes through t(),
   every miss reads English. The Settings control is a SELECT for the same reason: a
   sliding switch stops being one at seven choices. */
const UI_LANGS=[
  {code:"en", label:"English"},
  {code:"pl", label:"Polski"}
];
const UI_STRINGS={};
UI_STRINGS.pl={
  "Always one language":"Zawsze jeden język",
  "The card keeps this language whatever the EN|PL toggle says, tokens included":"Karta zostaje w tym języku niezależnie od przełącznika EN|PL, razem z tokenami",
  "Fold this group away":"Zwiń tę grupę",
  "Show these cards":"Pokaż te karty",
  "Matching your intent":"Pasujące do intencji",
  "Put every setting back to its default? Your cards, edits, favourites and order are not touched.":"Przywrócić wszystkie ustawienia domyślne? Twoje karty, edycje, ulubione i kolejność pozostaną bez zmian.",
  "Settings reset":"Ustawienia przywrócone",
  "Put every setting on this screen back to what it ships with. Cards and edits are not affected.":"Przywraca wszystkie ustawienia z tego ekranu do stanu wyjściowego. Nie dotyczy kart ani edycji.",
  "maintenance␟hidden":"ukryte",
  "maintenance␟starred":"ulubione",
  "maintenance␟edited":"zmienione",
  "maintenance␟yours":"własne",
  "maintenance␟cards":"karty",
  "maintenance␟intents":"intencje",
  "maintenance␟content languages":"języki treści",
  "maintenance␟cards in one language":"karty w jednym języku",
  "maintenance␟scroll region":"przewijanie",
  "maintenance␟locked open":"zablokowane otwarte",
  "maintenance␟nothing":"nic",
  "maintenance␟categories renamed":"zmienione nazwy kategorii",
  "maintenance␟list width":"szerokość listy",
  "Columns":"Kolumny",
  "Auto":"Auto",
  "How many columns of cards to show. Auto fits as many as the window has room for.":"Ile kolumn kart pokazywać. Auto dopasowuje tyle, ile mieści się w oknie.",
  "Always a single column":"Zawsze jedna kolumna",
  "Always two columns, however wide the window is":"Zawsze dwie kolumny, niezależnie od szerokości okna",
  "As many as fit without making a column too narrow to read":"Tyle, ile się zmieści, bez zwężania kolumny poniżej czytelnej szerokości",
  "Narrowest column":"Najwęższa kolumna",
  "How narrow a column may get before Auto drops one. Wider means fewer, roomier columns.":"Jak wąska może być kolumna, zanim Auto usunie jedną. Szerzej to mniej, ale przestronniejszych kolumn.",
  "Columns fit the window":"Kolumny dopasowane do okna",
  "Single column":"Jedna kolumna",
  "Two columns":"Dwie kolumny",
  "maintenance␟Layout":"Układ",
  "maintenance␟window":"okno",
  "maintenance␟columns":"kolumny",
  "maintenance␟narrowest column":"najwęższa kolumna",
  "maintenance␟card / text width":"karta / tekst",
  "maintenance␟right padding":"prawy margines wewnętrzny",
  "INIT":"INICJAŁY",
  "GREET":"POWITANIE",
  "ACTION":"CZYNNOŚĆ",
  "TOPIC":"TEMAT",
  "DAYPART":"PORA DNIA",
  "Intent panel locked - open, and fixed width":"Panel intencji zablokowany - otwarty, ze stałą szerokością",
  "Intent panel locked off - hold Ctrl to show it":"Panel intencji zablokowany jako ukryty - przytrzymaj Ctrl, aby go pokazać",
  "Intent panel unlocked - may auto-hide, width draggable":"Panel intencji odblokowany - może chować się sam, szerokość można przeciągać",
  "Intent panel unlocked - hover the left edge to peek":"Panel intencji odblokowany - najedź na lewą krawędź, aby go podejrzeć",
  "Unlock - let the panel appear again when you hover the left edge":"Odblokuj - panel będzie znów pojawiał się po najechaniu na lewą krawędź",
  "Unlock - allow auto-hide on narrow windows, and allow the width to be dragged":"Odblokuj - pozwól na automatyczne chowanie w wąskich oknach i na przeciąganie szerokości",
  "Lock - stop the panel appearing on hover (Ctrl still shows it)":"Zablokuj - panel przestanie pojawiać się po najechaniu (Ctrl nadal go pokazuje)",
  "Hide the category bar, which is locked fully expanded when shown":"Ukryj pasek kategorii, który po pokazaniu pozostaje w pełni rozwinięty",
  "Hide the category bar; {KEY} peeks while it is hidden":"Ukryj pasek kategorii; {KEY} pozwala zerknąć, gdy jest ukryty",
  "Show the category bar under the header.":"Pokaż pasek kategorii pod nagłówkiem.",
  "Allow the category bar to auto-collapse to two lines when there are many categories.":"Pozwól, aby pasek kategorii zwijał się do dwóch linii, gdy kategorii jest dużo.",
  "Keep all category rows visible (no 2-line auto-collapse).":"Zachowaj wszystkie rzędy kategorii widoczne (bez zwijania do dwóch linii).",
  "Allow the intent panel to auto-hide on narrow windows (hover left edge or hold Ctrl to peek).":"Pozwól, aby panel intencji chował się sam w wąskich oknach (najedź na lewą krawędź lub przytrzymaj Ctrl, aby go podejrzeć).",
  "Keep the intent panel docked even when the window is narrow. Same as the lock at the top of the panel.":"Zachowaj panel intencji zadokowany nawet w wąskim oknie. To samo co blokada na górze panelu.",
  "maintenance␟name":"nazwa",
  "customer's name":"imię klienta",
  "agent's name":"imię agenta",
  "Role class":"Klasa roli",
  "Create a card":"Utwórz kartę",
  "Create a card in {CAT}":"Utwórz kartę w kategorii {CAT}",
  "No cards match.":"Brak pasujących kart.",
  "Press":"Naciśnij",
  "to clear macro search and intents.":"aby wyczyścić wyszukiwanie makr i intencje.",
  "Etiuda is empty.":"Etiuda jest pusta.",
  "Add a card to a category,":"Dodaj kartę do kategorii,",
  "Add a card to a category, or":"Dodaj kartę do kategorii albo",
  "you already have.":", który już masz.",
  "import a catalog":"zaimportuj katalog",
  "or":"albo",
  "to see how it works.":", aby zobaczyć, jak to działa.",
  "A catalog file next to Etiuda loads by itself when it is called":"Plik katalogu leżący obok Etiudy wczytuje się sam, gdy nazywa się",
  "Under any other name, bring it in with the button above.":"Pod inną nazwą wczytaj go przyciskiem powyżej.",
  "Etiuda loads the newest catalog from {FOLDER} on its own; a catalog kept anywhere else comes in through Import above.":"Etiuda sama wczytuje najnowszy katalog z {FOLDER}; katalog trzymany gdzie indziej trafia tu przez Importuj powyżej.",
  "Catalogs":"Katalogi",
  "Loaded":"Wczytany",
  "Newer":"Nowszy",
  "Written after the catalog you have":"Zapisany później niż wczytany katalog",
  "Open this folder":"Otwórz ten folder",
  "Change folder…":"Zmień folder…",
  "Eject":"Odłącz",
  "Put this catalog down and start empty":"Odłącz ten katalog i zacznij bez katalogu",
  "Load":"Wczytaj",
  "Choose the folder Etiuda reads catalogs from":"Wybierz folder, z którego Etiuda czyta katalogi",
  "That setting could not be saved.":"Nie udało się zapisać tego ustawienia.",
  "{FILE} is not a catalog Etiuda can read.":"{FILE} nie jest katalogiem, który Etiuda potrafi odczytać.",
  "{FILE} could not be read.":"Nie udało się odczytać pliku {FILE}.",
  "The catalog you import stays in this browser, ready whenever you come back.":"Wczytany katalog zostaje w tej przeglądarce i czeka, aż wrócisz.",
  "Add a card to {CAT}":"Dodaj kartę do kategorii {CAT}",
  "Clear search text":"Wyczyść tekst wyszukiwania",
  "not linked to your intent":"niepowiązane z Twoją intencją",
  "also mentions your search":"wspominają też Twoje zapytanie",
  "A search ranks the cards by relevance; clear it to order them yourself":"Wyszukiwanie porządkuje karty według trafności; po jego wyczyszczeniu ustalisz kolejność samodzielnie",
  "Drag header to reorder within the same highlight group":"Przeciągnij nagłówek, aby zmienić kolejność w tej samej grupie podświetlenia",
  "Drag header to reorder within the same highlight group; same category only":"Przeciągnij nagłówek, aby zmienić kolejność w tej samej grupie podświetlenia; tylko w tej samej kategorii",
  "{N} hidden":"ukrytych: {N}",
  "none":"brak",
  "Split by blank lines into alternatives":"Dziel pustymi liniami na warianty",
  "Ordered sequence (STEP badges)":"Ponumerowana sekwencja (znaczniki KROK)",
  "{PAX} as first name only":"{PAX} jako samo imię",
  "Linked to every {INT}":"Powiązanie ze wszystkimi {INT}",
  "Top of the {INT} group":"Na górze grupy {INT}",
  "steps":"kroki",
  "alt":"alt",
  /* Two senses, one English phrase: the agent typing their own name is asked for a first
     name, and a card flag says the customer's token is cut down to one. The second takes a
     context key, because Polish cannot say both with one word. */
  "first name":"imię",
  "pax␟first name":"tylko imię",
  "every intent":"każda intencja",
  "top":"góra",
  "{L} only":"tylko {L}",
  "nothing set":"nic nie ustawiono",
  "none (shared)":"brak (wspólna)",
  "unnamed (shared)":"bez nazwy (wspólna)",
  "catalog name only":"tylko nazwa katalogu",
  "Unnamed catalog":"Katalog bez nazwy",
  "Collapse":"Zwiń",
  "Expand":"Rozwiń",
  "Supporting category, relevant regardless of the intent":"Kategoria wspierająca, przydatna niezależnie od intencji",
  "Make this a supporting category, relevant regardless of the intent":"Ustaw jako kategorię wspierającą, przydatną niezależnie od intencji",
  "Un-hide every hidden card":"Odkryj wszystkie ukryte karty",
  "Un-hide every hidden intent":"Odkryj wszystkie ukryte intencje",
  "Nothing is hidden":"Nic nie jest ukryte",
  "Engine":"Silnik",
  "Catalog":"Katalog",
  "Storage":"Pamięć",
  "Display":"Wyświetlanie",
  "Personal state":"Stan osobisty",
  "version":"wersja",
  "running from":"uruchomiona z",
  "running in":"uruchomiona w",
  "showing":"pokazywane",
  "file watch":"obserwacja pliku",
  "not supported here":"nieobsługiwane w tej przeglądarce",
  "unknown":"nieznana",
  "local memory used":"użyta pamięć lokalna",
  "theme":"motyw",
  "edition":"edycja",
  "cards / macros":"karty / makra",
  "intents / categories":"intencje / kategorie",
  "layout rungs":"szczeble układu",
  "reduced motion":"ograniczone animacje",
  "state":"stan",
  "panel width cap":"limit szerokości panelu",
  "dock threshold":"próg dokowania",
  "shortcuts rebound":"zmienione skróty",
  "tabs":"rozmowy",
  "sample untouched":"przykład nietknięty",
  "blur effects":"efekty rozmycia",
  "on":"wł.",
  "off":"wył.",
  "yes":"tak",
  "no":"nie",
  "dark (system)":"ciemny (systemowy)",
  "light (system)":"jasny (systemowy)",
  "dark (chosen)":"ciemny (wybrany)",
  "light (chosen)":"jasny (wybrany)",
  "docked":"zadokowany",
  "hidden / overlay":"ukryty / nakładka",
  "off (rescue)":"wył. (ratunek)",
  "(none loaded)":"(nie wczytano)",
  "system":"systemowy",
  "unavailable":"niedostępne",
  "IN-MEMORY ONLY - edits last only until this tab closes":"TYLKO W PAMIĘCI - zmiany przetrwają do zamknięcia tej karty przeglądarki",
  "IN-MEMORY ONLY":"TYLKO W PAMIĘCI",
  "ACTIVE":"AKTYWNE",
  "Tab":"Rozmowa",
  "Step 1":"Krok 1",
  "STEP":"KROK",
  "step":"krok",
  "Copied {WHAT} from {TITLE}":"Skopiowano {WHAT} z: {TITLE}",
  "All":"Wszystkie",
  "cards":"karty",
  "categories":"kategorie",
  "intent":"intencja",
  "copy":"kopiuj",
  "other language":"drugi język",
  "facts":"fakty",
  "rail":"panel",
  "clear":"wyczyść",
  "customise in":"dostosuj w",
  "→ Settings → Keyboard shortcuts":"→ Ustawienia → Skróty klawiszowe",
  "· Etiuda":"· Etiuda",
  "Clear tab fields":"Wyczyść pola rozmowy",
  "Close tab":"Zamknij rozmowę",
  "Clear tab":"Wyczyść rozmowę",
  "Add tab":"Dodaj rozmowę",
  "and":"i",
  "Searched for":"Szukano",
  "you typed":"wpisano",
  "Drag to reorder: intents in the side panel (double-click its title to reset), a card header within its highlight group (intent-linked / favourited / both / regular), or alternative and step macros inside a card (EN and PL stay aligned). Show or hide the panel from the":"Przeciągnij, aby zmienić kolejność: intencje w panelu bocznym (kliknij dwukrotnie jego tytuł, aby ją przywrócić), nagłówek karty w obrębie jej grupy podświetlenia (powiązane z intencją / ulubione / oba / zwykłe) albo warianty i kroki wewnątrz karty (EN i PL pozostają zgodne). Panel pokażesz lub ukryjesz z",
  "Quick facts - fees and deadlines.":"Szybkie fakty - opłaty i terminy.",
  "- cards, intent panel, category pills, shortcuts.":"- karty, panel intencji, pastylki kategorii, skróty.",
  "toggles theme.":"przełącza motyw.",
  "Toggle theme":"Przełącz motyw",
  "Switch language":"Przełącz język kart",
  "int":"int",
  "In a supporting category, relevant regardless of the intent":"W kategorii wspierającej, przydatna niezależnie od intencji",
  "sup":"wsp",
  "fav":"fav",
  "mod":"mod",
  "Put this card away: it greys out at the foot of this category and loses its star":"Odłóż tę kartę: zszarzeje na końcu swojej kategorii i straci gwiazdkę",
  "Put this card away: it greys out at the foot of this category":"Odłóż tę kartę: zszarzeje na końcu swojej kategorii",
  "Put this card away":"Odłóż tę kartę",
  "Changed or added by you, not what the catalog shipped":"Zmienione lub dodane przez Ciebie, nie z katalogu",
  "Add an intent":"Dodaj intencję",
  "Remove from Favourites":"Usuń z Ulubionych",
  "Add to Favourites":"Dodaj do Ulubionych",
  "Lock - keep the panel docked on narrow windows, and fix its width":"Zablokuj - panel pozostanie zadokowany w wąskich oknach, z ustaloną szerokością",
  "Unlock the intent panel":"Odblokuj panel intencji",
  "Lock the intent panel open and fix its width":"Zablokuj panel intencji otwarty i ustal jego szerokość",
  "Hold Ctrl to show intents":"Przytrzymaj Ctrl, aby pokazać intencje",
  "Click · drag to reorder ·":"Kliknij · przeciągnij kolejność ·",
  "for several":"dla kilku",
  "English":"English",
  "Polski":"Polski",
  "Maxim Gwiazda":"Maxim Gwiazda",
  "Etiuda Source-Available Licence 1.0":"Etiuda Source-Available Licence 1.0",
  "Created by":"Autor:",
  "· free for personal use":"· bezpłatnie do użytku osobistego",
  "Tour {N} / {TOTAL}":"Przewodnik {N} / {TOTAL}",
  "Finish":"Zakończ",
  "Welcome to Etiuda":"Witaj w Etiudzie",
  "Your agent name":"Twoja nazwa agenta",
  "Chat tabs":"Rozmowy",
  "Customer name and role":"Imię klienta i rola",
  "Intent clause":"Klauzula intencji",
  "Category pills":"Pastylki kategorii",
  "Intent panel":"Panel intencji",
  "Cards":"Karty",
  "Put a card away":"Odkładanie karty na bok",
  "Edit a card":"Edycja karty",
  "A card of your own":"Twoja własna karta",
  "The card editor":"Edytor karty",
  "English / Polish":"Angielski / polski",
  "Light and dark":"Jasny i ciemny",
  "You are set":"Wszystko gotowe",
  "A live-chat macro bank for support agents. This short tour points at the main controls; you can skip it at any time with <kbd>Esc</kbd>.":"Bank makr do czatu na żywo dla agentów wsparcia. Ten krótki przewodnik pokazuje główne elementy - możesz go pominąć w każdej chwili klawiszem <kbd>Esc</kbd>.",
  "Type the name customers should see, exactly as you want it to appear; <span class=\"fillmiss\">AGENT</span> reproduces it verbatim. Internal comments sign with your initials as /<span class=\"fillmiss\">INIT</span>.":"Wpisz imię, które mają widzieć klienci, dokładnie w takiej formie - <span class=\"fillmiss\">AGENT</span> wstawia je bez zmian. Komentarze wewnętrzne podpisywane są Twoimi inicjałami jako /<span class=\"fillmiss\">INIT</span>.",
  "One tab per chat: {KEY} steps to the next one from anywhere, {NEW} opens one. Each tab keeps its own language, <span class=\"fillmiss\">PAX</span>, <span class=\"fillmiss\">INTENT</span>, <span class=\"fillmiss\">ROLE</span> and categories, and its dot takes the colour of its category filter; settings like the theme and your agent name are shared. Drag a tab to reorder.":"Po jednej rozmowie na czat: {KEY} przechodzi do następnej z dowolnego miejsca, {NEW} otwiera nową. Każda pamięta własny język, <span class=\"fillmiss\">PAX</span>, <span class=\"fillmiss\">INTENT</span>, <span class=\"fillmiss\">ROLE</span> i kategorie - kropka przy rozmowie przyjmuje kolor jej filtra kategorii - a ustawienia takie jak motyw i nazwa agenta są wspólne. Przeciągnij rozmowę, aby zmienić kolejność.",
  "Paste the name exactly as the chat gives it - full name, surname, ALL CAPS, all fine. Etiuda tidies it, and wherever a card addresses the customer it uses only the first name, declined in Polish automatically (ANNA KOWALSKA → <b>Anno</b>). Fills <span class=\"fillmiss\">PAX</span>. The wheel beside it sets who you are speaking to, relative to whoever the chat is about, and fills <span class=\"fillmiss\">ROLE</span> in internal comments. Click or scroll it to change; the empty notch clears it.":"Wklej imię dokładnie tak, jak podaje je czat - pełne dane, nazwisko, WERSALIKI, wszystko jedno. Etiuda je porządkuje, a tam gdzie karta zwraca się do klienta, używa samego imienia, odmienionego po polsku automatycznie (ANNA KOWALSKA → <b>Anno</b>). Wypełnia <span class=\"fillmiss\">PAX</span>. Kółko obok określa, z kim rozmawiasz, w odniesieniu do osoby, której dotyczy czat, i wypełnia <span class=\"fillmiss\">ROLE</span> w komentarzach wewnętrznych. Kliknij je lub przewiń, aby zmienić; pusta pozycja czyści wybór.",
  "Filter cards by category; <kbd>Ctrl</kbd>+click keeps several. The rings say why a pill stands out: <b class=\"t-go\">green</b> - it holds a card linked to your intent; <b class=\"t-acc\">blue</b> - a supporting category, useful whatever the customer asked. <kbd>←</kbd> <kbd>→</kbd> step through them, from the search box too. Drag pills to reorder; double-click <span class=\"t-pill\"><span data-icon=\"all\"></span>All</span> to reset the order.":"Filtruj karty według kategorii; <kbd>Ctrl</kbd>+klik zostawia kilka naraz. Obwódki mówią, dlaczego pastylka się wyróżnia: <b class=\"t-go\">zielona</b> - zawiera kartę powiązaną z Twoją intencją; <b class=\"t-acc\">niebieska</b> - kategoria wspierająca, przydatna niezależnie od pytania klienta. <kbd>←</kbd> <kbd>→</kbd> przechodzą między nimi, także z pola wyszukiwania. Przeciągaj pastylki, aby zmienić kolejność; kliknij dwukrotnie <span class=\"t-pill\"><span data-icon=\"all\"></span>Wszystkie</span>, aby ją przywrócić.",
  "Click to pick an intent, or <kbd>Ctrl</kbd>+click to pick several; picks stack at the top of the panel and the rest of the list scrolls beneath them, so a pick never leaves the screen. The pointer and the arrow keys share one mark. Drag to reorder, star to pin favourites to the top. Hold <kbd>Ctrl</kbd> over a star and it becomes an edit button; hold <kbd>Shift</kbd> and it becomes a hide button; hidden intents grey out and sink to the bottom, and the closed eye brings them back. The <span data-icon=\"pin\"></span> lock at the top keeps the panel open on narrow windows.":"Kliknij, aby wybrać intencję, albo <kbd>Ctrl</kbd>+kliknij, aby wybrać kilka; wybrane układają się na górze panelu, a reszta listy przewija się pod nimi, więc wybór nigdy nie znika z ekranu. Wskaźnik myszy i strzałki dzielą jedno zaznaczenie. Przeciągaj, aby zmieniać kolejność, gwiazdką przypinasz ulubione na górę. Przytrzymaj <kbd>Ctrl</kbd> nad gwiazdką, a zmieni się w przycisk edycji; przytrzymaj <kbd>Shift</kbd>, a zmieni się w przycisk ukrywania - ukryte intencje szarzeją i spadają na dół, a zamknięte oko je przywraca. Blokada <span data-icon=\"pin\"></span> na górze utrzymuje panel otwarty w wąskich oknach.",
  "Click a macro to copy it, or use <kbd>↑</kbd> <kbd>↓</kbd> between macros and <kbd>Enter</kbd> to copy (<kbd>Shift</kbd>+<kbd>Enter</kbd> other language). A card holding several shows <b>1/2</b> or <b>STEP 1/3</b>; each macro copies on its own. The small tags say why a card is where it is: <span class=\"cbadge hit\">int</span> linked to your intent, <span class=\"cbadge cat\">sup</span> a supporting category, <span class=\"cbadge fav\">fav</span> a favourite, <span class=\"cbadge ed\">mod</span> changed or added on this computer. Hover one for the full wording. Drag the card header to reorder within the same highlight group.":"Kliknij makro, aby je skopiować, albo poruszaj się między makrami klawiszami <kbd>↑</kbd> <kbd>↓</kbd> i kopiuj przez <kbd>Enter</kbd> (<kbd>Shift</kbd>+<kbd>Enter</kbd> - drugi język). Karta z kilkoma makrami pokazuje <b>1/2</b> lub <b>KROK 1/3</b> - każde makro kopiuje się osobno. Małe znaczniki mówią, skąd karta ma swoje miejsce: <span class=\"cbadge hit\">int</span> powiązana z Twoją intencją, <span class=\"cbadge cat\">wsp</span> kategoria wspierająca, <span class=\"cbadge fav\">fav</span> ulubiona, <span class=\"cbadge ed\">mod</span> zmieniona lub dodana na tym komputerze - najedź na znacznik, aby zobaczyć pełny opis. Przeciągnij nagłówek karty, aby zmienić kolejność w obrębie tej samej grupy podświetlenia.",
  "The star lifts a card to the top of wherever it already is: to the head of its category, to the head of its highlight group when an intent is selected, and on <span class=\"t-pill\"><span data-icon=\"all\"></span>All</span> to a <b class=\"t-fav\"><span data-icon=\"star\"></span>Favourites</b> block at the top of the list. The gold star and the <span class=\"cbadge fav\">fav</span> tag mark it - separate from the <b class=\"t-go\">green</b> of an intent link and the <b class=\"t-acc\">blue</b> of a supporting category.":"Gwiazdka podnosi kartę na szczyt tego miejsca, w którym już jest: na czoło swojej kategorii, na czoło grupy podświetlenia, gdy wybrano intencję, a w widoku <span class=\"t-pill\"><span data-icon=\"all\"></span>Wszystkie</span> do bloku <b class=\"t-fav\"><span data-icon=\"star\"></span>Ulubione</b> na górze listy. Oznacza ją złota gwiazdka i znacznik <span class=\"cbadge fav\">fav</span> - niezależnie od <b class=\"t-go\">zieleni</b> powiązania z intencją i <b class=\"t-acc\">błękitu</b> kategorii wspierającej.",
  "The eye puts a card away: it greys out and sinks to the foot of its own category, and it shows nowhere else - not in All, and not in a search. Open that category with the box empty and the same button brings it back. Putting a starred card away also unstars it. Nothing is deleted; <b class=\"t-bad\">Delete</b> lives only in the editor and in Library.":"Oko odkłada kartę na bok: karta szarzeje i spada na dół swojej kategorii, a poza tym nie pojawia się nigdzie - ani we Wszystkich, ani w wyszukiwaniu. Otwórz tę kategorię z pustym polem, a ten sam przycisk ją przywróci. Odłożenie karty z gwiazdką usuwa też gwiazdkę. Nic nie jest usuwane; <b class=\"t-bad\">Usuń</b> istnieje wyłącznie w edytorze i w Bibliotece.",
  "The pencil opens the card for editing - both languages, the internal note, the search keywords, and everything about how it behaves. Editing a built-in card writes a personal override <b>on this computer</b>; the catalog itself is untouched, and the editor's <b>Reset</b> brings the original wording back whenever you want it.":"Ołówek otwiera kartę do edycji - oba języki, notatkę wewnętrzną, słowa kluczowe i wszystko, co dotyczy jej zachowania. Edycja karty wbudowanej zapisuje własną wersję <b>na tym komputerze</b>; sam katalog pozostaje nienaruszony, a <b>Przywróć</b> w edytorze w każdej chwili odtwarza pierwotną treść.",
  "The <b>+</b> in the corner starts a new card from wherever you are - the same screen the pencil opens, empty. Inside a category it files into that one; under <span class=\"t-pill\"><span data-icon=\"all\"></span>All</span> the editor asks which, in its <span class=\"t-sec\">Category</span> section.":"<b>+</b> w rogu zaczyna nową kartę z dowolnego miejsca - ten sam ekran, który otwiera ołówek, tylko pusty. Wewnątrz kategorii trafi właśnie do niej; w widoku <span class=\"t-pill\"><span data-icon=\"all\"></span>Wszystkie</span> edytor zapyta, do której, w sekcji <span class=\"t-sec\">Kategoria</span>.",
  "<span class=\"t-sec\">Content</span> holds the text in both languages, with the internal note. Folded below: <span class=\"t-sec\">Keywords</span>, <span class=\"t-sec\">Category</span>, <span class=\"t-sec\">Linked intents</span> - which makes a card ring green under an intent, and marks its category relevant to those intents - and <span class=\"t-sec\">Advanced</span>, holding alternatives, ordered steps and the ring flags. <b>Cancel</b> leaves everything as it was. A row in <b>Library</b> opens the same screen.":"<span class=\"t-sec\">Treść</span> zawiera tekst w obu językach wraz z notatką wewnętrzną. Zwinięte poniżej: <span class=\"t-sec\">Słowa kluczowe</span>, <span class=\"t-sec\">Kategoria</span>, <span class=\"t-sec\">Powiązane intencje</span> - to one sprawiają, że karta świeci na zielono przy intencji, i oznaczają jej kategorię jako istotną dla tych intencji - oraz <span class=\"t-sec\">Zaawansowane</span>, gdzie są warianty, ponumerowane kroki i znaczniki obwódek. <b>Anuluj</b> zostawia wszystko bez zmian. Wiersz w <b>Bibliotece</b> otwiera ten sam ekran.",
  "Switch the language of macro text on screen; {KEY} flips it from anywhere. Intent clauses that come from the list follow <b class=\"t-acc\">EN</b>/<b class=\"t-pl\">PL</b>; free-typed intent text does not. A card with no Polish shows its English rather than a gap, so only the first language is ever required.":"Przełącz język treści makr na ekranie - {KEY} zmienia go z dowolnego miejsca. Klauzule intencji wybrane z listy podążają za <b class=\"t-acc\">EN</b>/<b class=\"t-pl\">PL</b>; intencja wpisana ręcznie nie. Karta bez polskiej wersji pokazuje angielską zamiast luki, więc wymagany jest tylko pierwszy język.",
  "Fees, deadlines, and useful links - click a link-like token to copy the full URL. You can edit this text for yourself; it stays in this browser.":"Opłaty, terminy i przydatne odnośniki - kliknij element wyglądający jak odnośnik, aby skopiować pełny adres. Możesz zmienić ten tekst na własny użytek; zostaje w tej przeglądarce.",
  "Etiuda follows your system's setting, and keeps following it. Clicking here is what turns that into a choice, and it is remembered from then on.":"Etiuda podąża za ustawieniem Twojego systemu i robi to nadal. Dopiero kliknięcie tutaj zamienia to w wybór, który od tej pory jest zapamiętany.",
  "Everything that is not a card. <b>Library</b> is where the content lives, <b>Settings</b> holds the interface language, the appearance and the keyboard shortcuts, and the entries in the middle hide or lock the intent panel and the category bar. Hold <kbd>Ctrl</kbd> to peek at either while it is hidden. This tour is here too, under <b>Show tour…</b>.":"Wszystko, co nie jest kartą. W <b>Bibliotece</b> mieszka treść, <b>Ustawienia</b> zawierają język interfejsu, wygląd i skróty klawiszowe, a pozycje w środku ukrywają lub blokują panel intencji i pasek kategorii. Przytrzymaj <kbd>Ctrl</kbd>, aby podejrzeć jedno lub drugie, gdy jest ukryte. Ten przewodnik też tu jest, pod <b>Pokaż przewodnik…</b>.",
  "<b><span data-icon=\"settings\"></span> → Library</b> opens this, and it is where the content lives. <span class=\"t-sec\">Categories &amp; cards</span> lists everything you have, grouped - add, edit, hide, delete, or drag a card into another category. <span class=\"t-sec\">Intents</span> does the same for the intent list. <span class=\"t-sec\">ROLE suggestions</span> fills the ROLE box. <span class=\"t-sec\">Catalog &amp; data</span> saves what you have to a file, brings someone else's in, or bakes the lot into a single copy to hand on.":"<b><span data-icon=\"settings\"></span> → Biblioteka</b> otwiera ten ekran i to tu mieszka treść. <span class=\"t-sec\">Kategorie i karty</span> wymienia wszystko, co masz, pogrupowane - dodawaj, edytuj, ukrywaj, usuwaj albo przeciągnij kartę do innej kategorii. <span class=\"t-sec\">Intencje</span> robi to samo z listą intencji. <span class=\"t-sec\">Podpowiedzi ROLE</span> wypełnia pole ROLE. <span class=\"t-sec\">Katalog i dane</span> zapisuje to, co masz, do pliku, wczytuje cudzy katalog albo zapieka całość w jedną kopię do przekazania dalej.",
  "<b><span data-icon=\"settings\"></span> → Settings</b> is the interface itself. <span class=\"t-sec\">Personal</span> carries your name and the language of the buttons and menus; the macros have their own switch in the header. <span class=\"t-sec\">Appearance</span> holds the theme, the columns, the blur and the animations; <span class=\"t-sec\">Layout</span> says what stays docked and what may hide itself when space is short; <span class=\"t-sec\">Keyboard shortcuts</span> rebinds any chord when you click it. <b>Reset defaults</b> puts this screen back to what it ships with and touches no card.":"<b><span data-icon=\"settings\"></span> → Ustawienia</b> to sam interfejs. <span class=\"t-sec\">Osobiste</span> zawiera Twoje imię oraz język przycisków i menu - makra mają własny przełącznik w nagłówku. <span class=\"t-sec\">Wygląd</span> obejmuje motyw, kolumny, efekty rozmycia i animacje; <span class=\"t-sec\">Układ</span> mówi, co pozostaje zadokowane, a co może się schować, gdy brakuje miejsca; <span class=\"t-sec\">Skróty klawiszowe</span> zmienia dowolną kombinację po kliknięciu. <b>Przywróć domyślne</b> cofa ten ekran do stanu wyjściowego i nie dotyka żadnej karty.",
  "Shortcuts live under <span data-icon=\"settings\"></span> <b>→ About Etiuda</b>, and <b>Show tour…</b> in the same menu brings this back. When in doubt, your team lead is the one to ask.":"Skróty klawiszowe znajdziesz pod <span data-icon=\"settings\"></span> <b>→ O Etiudzie</b>, a <b>Pokaż przewodnik…</b> w tym samym menu otwiera go ponownie. W razie wątpliwości pytaj swojego team leadera.",
  "Categories & cards":"Kategorie i karty",
  "Intent":"Intencja",
  "Intents":"Intencje",
  "ROLE suggestions":"Podpowiedzi ROLE",
  "Catalog & data":"Katalog i dane",
  "Content":"Treść",
  "Category":"Kategoria",
  "Linked intents":"Powiązane intencje",
  "Advanced":"Zaawansowane",
  "Favourites":"Ulubione",
  "Sample catalog":"Przykładowy katalog",
  "Keys":"Klawisze",
  "No catalog loaded - Etiuda is empty.":"Nie wczytano katalogu - Etiuda jest pusta.",
  "About Etiuda · Version {V} · <span class='nw'>Etiuda Source-Available Licence 1.0</span>, free for personal use · © 2026 Maxim Gwiazda":"O Etiudzie · Wersja {V} · <span class='nw'>Etiuda Source-Available Licence 1.0</span>, bezpłatnie do użytku osobistego · © 2026 Maxim Gwiazda",
  "An interactive tour of the main controls, about a minute.":"Interaktywny przewodnik po głównych elementach, około minuty.",
  "Toggle language":"Przełącz język",
  "Next tab":"Następna rozmowa",
  "New tab":"Nowa rozmowa",
  "Open the Menu":"Otwórz Menu",
  "Your name":"Twoje imię",
  "Personal":"Osobiste",
  "Last sync":"Ostatnia synchronizacja",
  "Later":"Później",
  "Focus {PAX}":"Kursor w {PAX}",
  "Focus ROLE":"Kursor w ROLE",
  "Toggle intent panel":"Przełącz panel intencji",
  "Toggle category pills":"Przełącz pasek kategorii",
  "Clear intent":"Wyczyść intencję",
  "Clear the intent":"Wyczyść intencję",
  "Internal note":"Notatka wewnętrzna",
  "This category is empty.":"Ta kategoria jest pusta.",
  "to create a card here.":"aby utworzyć tu kartę.",
  "New card":"Nowa karta",
  "Open the editor for a new card, in the chosen category":"Otwiera edytor nowej karty, w wybranej kategorii",
  "Notes on hover":"Notatki po najechaniu",
  "Open a card's internal note when the pointer rests on the card.":"Otwiera notatkę wewnętrzną karty, gdy kursor na niej spocznie.",
  "The note opens by itself, and the card shows no i":"Notatka otwiera się sama, a karta nie pokazuje litery i",
  "The i on the card opens the note":"Litera i na karcie otwiera notatkę",
  "Notes open on hover":"Notatki otwierają się po najechaniu",
  "Notes open from the i":"Notatki otwiera litera i",
  "Clear the chosen intents ({N})":"Wyczyść wybrane intencje ({N})",
  "Reveal / expand categories":"Pokaż / rozwiń kategorie",
  "Maintenance panel":"Panel konserwacji",
  "Select search text":"Zaznacz tekst wyszukiwania",
  "{PAX} in the vocative":"{PAX} w wołaczu",
  "Polish only: declines the name into the vocative, the form Polish uses to address someone. Only the first name declines; a surname is left as written.":"Tylko dla polskiego: odmienia imię w wołaczu, czyli w formie, której polszczyzna używa w zwrocie do kogoś. Odmieniane jest tylko imię, a nazwisko pozostaje bez zmian.",
  "vocative":"wołacz",
  "Previous card":"Poprzednia karta",
  "Next card":"Następna karta",
  "Previous category":"Poprzednia kategoria",
  "Next category":"Następna kategoria",
  "Top of the list":"Początek listy",
  "Bottom of the list":"Koniec listy",
  "First category":"Pierwsza kategoria",
  "Last category":"Ostatnia kategoria",
  "Copy focused card":"Kopiuj zaznaczoną kartę",
  "Copy other language":"Kopiuj w drugim języku",
  "Escape / clear":"Escape / wyczyść",
  "Switch the cards between English and Polish":"Przełącza karty między angielskim a polskim",
  "Switch to the next chat tab, round to the first after the last":"Przełącza na następną rozmowę, a po ostatniej wraca do pierwszej",
  "Open a fresh chat tab":"Otwiera nową rozmowę",
  "Open or close the fees panel":"Otwiera lub zamyka panel opłat",
  "Open or close the Menu, from anywhere on the screen":"Otwiera lub zamyka Menu, z dowolnego miejsca na ekranie",
  "Edit the customer first name":"Edytuje imię klienta",
  "Edit the comment actor":"Edytuje wykonawcę w komentarzu",
  "Show or hide the left intent list":"Pokazuje lub ukrywa lewą listę intencji",
  "Show or hide the category bar":"Pokazuje lub ukrywa pasek kategorii",
  "Deselect every chosen intent":"Odznacza wszystkie wybrane intencje",
  "Clear the category filter":"Czyści filtr kategorii",
  "Hold Ctrl (Cmd on Mac): show the pills when hidden, or expand them past two rows":"Przytrzymaj Ctrl (Cmd na Macu): pokazuje ukryte kategorie lub rozwija je poza dwa rzędy",
  "Readings about this machine, and rescue switches":"Odczyty o tej maszynie i przełączniki ratunkowe",
  "Select everything in the INTENT / MACRO box, without clicking into it first":"Zaznacza całą treść pola INTENT / MACRO bez klikania w nie",
  "Move focus to the previous copyable macro (alt / step / single)":"Przenosi kursor na poprzednie makro do skopiowania (wariant / krok / pojedyncze)",
  "Move focus to the next copyable macro (alt / step / single)":"Przenosi kursor na następne makro do skopiowania (wariant / krok / pojedyncze)",
  "Select the previous category pill (All, then the categories)":"Wybiera poprzednią kategorię (Wszystkie, potem kategorie)",
  "Select the next category pill (All, then the categories)":"Wybiera następną kategorię (Wszystkie, potem kategorie)",
  "Move the mark to the top of its list, then across to the other one":"Przenosi zaznaczenie na początek swojej listy, a stamtąd na drugą listę",
  "Move the mark to the bottom of its list, then across to the other one":"Przenosi zaznaczenie na koniec swojej listy, a stamtąd na drugą listę",
  "Select the first category, skipping All and any the search has emptied":"Wybiera pierwszą kategorię, pomijając Wszystkie i te opróżnione przez wyszukiwanie",
  "Select the last category, skipping any the search has emptied":"Wybiera ostatnią kategorię, pomijając te opróżnione przez wyszukiwanie",
  "Copy the focused macro in the active language":"Kopiuje zaznaczone makro w aktywnym języku",
  "Copy the focused macro in the other language":"Kopiuje zaznaczone makro w drugim języku",
  "Sheds one thing per press: panels, then search, then intents, then all tabs":"Zdejmuje jedną rzecz na naciśnięcie: panele, potem wyszukiwanie, potem intencje, potem wszystkie rozmowy",
  "Customers see \"{NAME}\", and comments sign /{INIT}":"Klienci widzą \"{NAME}\", a komentarze podpisują się /{INIT}",
  "The name customers see, exactly as you type it; comments sign with its initials":"Nazwa, którą widzą klienci, dokładnie tak, jak ją wpiszesz; komentarze podpisują się jej inicjałami",
  "Panel is locked open (always docked). Hide turns it off entirely.":"Panel jest zablokowany otwarty (zawsze zadokowany). Ukryj wyłącza go całkowicie.",
  "Prefer showing the intent panel when the window is wide. On narrow windows it auto-hides; hover the left edge or hold Ctrl to peek. Use the lock at the top of the panel, or Settings, to keep it open.":"Pokazuj panel intencji, gdy okno jest szerokie. W wąskich oknach chowa się sam; najedź na lewą krawędź lub przytrzymaj Ctrl, aby go podejrzeć. Aby został otwarty, użyj blokady na górze panelu lub Ustawień.",
  "Intent panel off. Hold Ctrl to peek the intent list as an overlay.":"Panel intencji wyłączony. Przytrzymaj Ctrl, aby podejrzeć listę intencji jako nakładkę.",
  "Polish cards - switch to English":"Karty po polsku - przełącz na angielski",
  "English cards - switch to Polish":"Karty po angielsku - przełącz na polski",
  "Click to filter · Ctrl+click to add/remove · drag to reorder":"Kliknij, aby filtrować · Ctrl+kliknięcie dodaje/usuwa · przeciągnij, aby zmienić kolejność",
  "Green ring: holds a card linked to the chosen intent":"Zielona obwódka: zawiera kartę powiązaną z wybraną intencją",
  "Blue ring: a supporting category":"Niebieska obwódka: kategoria wspierająca",
  "Click any macro to copy":"Kliknij dowolne makro, aby skopiować",
  "… are alternatives, copied one at a time.":"… to warianty, kopiowane pojedynczo.",
  "fills from the name box;":"wypełnia się z pola imienia;",
  "from the agent name;":"z nazwy agenta;",
  "from the side panel, from the chips under the opener when the panel is off, or from what you type. A listed intent follows EN|PL; typed text does not. Typing in SEARCH ranks intents and filters cards in both languages.":"z panelu bocznego, z chipów pod kartą otwierającą, gdy panel jest ukryty, albo z tego, co wpiszesz. Intencja z listy podąża za EN|PL; tekst wpisany ręcznie już nie. Pisanie w SZUKAJ układa intencje i filtruje karty w obu językach.",
  "is the subject of the chat as a noun phrase: where":"to temat rozmowy jako wyrażenie rzeczownikowe: tam, gdzie",
  "names an act, this names a thing.":"nazywa czynność, to nazywa rzecz.",
  "is what was DONE, for internal comments. Both are set per intent in its editor.":"to opis tego, co ZOSTAŁO ZROBIONE, do komentarzy wewnętrznych. Oba ustawia się przy każdej intencji, w jej edytorze.",
  "just that macro":"tylko to makro",
  "- cards badged":"- karty oznaczone",
  "are alternatives and copy one at a time.":"to warianty i kopiują się pojedynczo.",
  "Different catalog found":"Znaleziono inny katalog",
  "Older catalog found":"Znaleziono starszy katalog",
  "The file beside Etiuda is an earlier edition than the one you have.":"Plik obok Etiudy to wcześniejsze wydanie niż to, które masz.",
  "Load it anyway":"Wczytaj mimo to",
  "Updated catalog found":"Znaleziono zaktualizowany katalog",
  "Watching":"Obserwowany:",
  "Check for updates":"Sprawdź aktualizacje",
  "Read that file again and offer it if it has changed":"Przeczytaj ten plik ponownie i zaproponuj go, jeśli się zmienił",
  "Stop watching":"Przestań obserwować",
  "No longer watching that file.":"Ten plik nie jest już obserwowany.",
  "No catalog file is being watched.":"Żaden plik katalogu nie jest obserwowany.",
  "Etiuda needs permission to read that file again.":"Etiuda potrzebuje ponownej zgody na odczyt tego pliku.",
  "That file is not a catalog Etiuda can read.":"Tego pliku Etiuda nie potrafi odczytać jako katalogu.",
  "That file matches the catalog you already have.":"Ten plik jest zgodny z katalogiem, który już masz.",
  "Could not read the watched file.":"Nie udało się odczytać obserwowanego pliku.",
  "The catalog beside Etiuda has changed since you loaded it.":"Katalog obok Etiudy zmienił się od czasu wczytania.",
  "Your own cards and edits are kept.":"Twoje karty i zmiany zostają.",
  "Load the update":"Wczytaj aktualizację",
  "You have {V}.":"Masz {V}.",
  "This is a newer copy of the catalog you already have, so your own cards and edits are kept.":"To nowsza kopia katalogu, który już masz, więc Twoje własne karty i zmiany zostaną zachowane.",
  "Load catalog?":"Wczytać katalog?",
  "The file beside Etiuda no longer matches what is loaded.":"Plik leżący obok Etiudy nie odpowiada już temu, co jest wczytane.",
  "Located as {FILE}.":"Znaleziony jako {FILE}.",
  "Located as {FILE} in {FOLDER}.":"Znaleziony jako {FILE} w {FOLDER}.",
  "{FILE} in {FOLDER}":"{FILE} w {FOLDER}",
  "Catalog file":"Plik katalogu",
  "Loading it replaces the catalog you have now.":"Wczytanie go zastąpi katalog, który masz teraz.",
  "Card added":"Karta dodana",
  "Card saved":"Karta zapisana",
  "Intent added":"Intencja dodana",
  "Intent saved":"Intencja zapisana",
  "Intent shown again":"Intencja pokazana ponownie",
  "Intent hidden - greyed and moved to the bottom":"Intencja ukryta - wyszarzona i przeniesiona na dół",
  "Put away - greyed at the foot of its category":"Odłożona - wyszarzona na dole swojej kategorii",
  "Put away - greyed at the foot of its category, unfavourited":"Odłożona - wyszarzona na dole swojej kategorii, usunięta z ulubionych",
  "1 card shown again":"1 karta pokazana ponownie",
  "{N} cards shown again":"Karty pokazane ponownie: {N}",
  "1 intent shown again":"1 intencja pokazana ponownie",
  "{N} intents shown again":"Intencje pokazane ponownie: {N}",
  "Categories shown":"Kategorie pokazane",
  "Categories hidden":"Kategorie ukryte",
  "Categories stay fully expanded":"Kategorie pozostają w pełni rozwinięte",
  "Categories may auto-collapse":"Kategorie mogą się zwijać automatycznie",
  "Intent panel shown":"Panel intencji pokazany",
  "Intent panel hidden":"Panel intencji ukryty",
  "Quick facts saved":"Szybkie fakty zapisane",
  "Quick facts match built-in default":"Szybkie fakty zgodne z wbudowanymi",
  "is now a supporting category":"jest teraz kategorią wspierającą",
  "is an ordinary category":"jest zwykłą kategorią",
  "No {LANG} version for this card":"Brak wersji {LANG} dla tej karty",
  "switch to {LANG} to use it":"przełącz na {LANG}, aby jej użyć",
  "Keeping the loaded catalog.":"Zachowano wczytany katalog.",
  "Starting empty. Load one any time from the Library.":"Start bez katalogu. Możesz go wczytać w każdej chwili z Biblioteki.",
  "{INTENT} set -":"Ustawiono {INTENT} -",
  "Clear Etiuda's local memory in this browser?":"Wyczyścić pamięć lokalną Etiudy w tej przeglądarce?",
  "Removes every personal card, intent, edit, hide, category rename and quick-facts edit,":"Usuwa wszystkie własne karty, intencje, zmiany, ukrycia, zmienione nazwy kategorii i zmiany w szybkich faktach,",
  "Catalog files on disk are not touched.":"Pliki katalogu na dysku pozostają nienaruszone.",
  "Etiuda restarts empty. If a catalog file sits beside it you will be asked whether to":"Etiuda uruchomi się pusta. Jeśli obok leży plik katalogu, zostaniesz zapytany, czy",
  "Import catalog":"Importuj katalog",
  "Load this catalog on this browser:":"Wczytać ten katalog w tej przeglądarce:",
  "It replaces the catalog loaded now. Personal card edits and custom cards on this":"Zastąpi wczytany katalog. Własne zmiany w kartach i własne karty w tej",
  "browser are cleared, because they belong to the catalog they were written against.":"przeglądarce zostaną usunięte, ponieważ należą do katalogu, dla którego powstały.",
  "Nothing on disk is changed. Etiuda reloads to apply it.":"Nic na dysku nie zostanie zmienione. Etiuda przeładuje się, aby to zastosować.",
  "Continue?":"Kontynuować?",
  "Changes every label in Etiuda, never the cards themselves":"Zmienia wszystkie etykiety w Etiudzie, nigdy samych kart",
  "Theme, blur effects and animations":"Motyw, efekty rozmycia i animacje",
  "What stays docked, and what may hide itself when space is short":"Co pozostaje zadokowane, a co może się schować, gdy brakuje miejsca",
  "Rebind any key combo. The keys the app itself needs are listed as fixed.":"Zmień dowolny skrót. Klawisze potrzebne samej aplikacji są oznaczone jako stałe.",
  "Always the light palette, whatever the computer asks for":"Zawsze jasna paleta, niezależnie od ustawień komputera",
  "Always the dark palette, whatever the computer asks for":"Zawsze ciemna paleta, niezależnie od ustawień komputera",
  "Follows your computer's light or dark setting, and changes with it":"Podąża za ustawieniem jasnym lub ciemnym komputera i zmienia się razem z nim",
  "Panels and the dialog backdrop stay blurred":"Panele i tło za oknami dialogowymi pozostają rozmyte",
  "Panels go flat and opaque, and a dialog only darkens what is behind it":"Panele stają się płaskie i nieprzezroczyste, a okno dialogowe tylko przyciemnia to, co za nim",
  "Everything moves as it was drawn to":"Wszystko porusza się tak, jak zaprojektowano",
  "Nothing moves; every change lands at once":"Nic się nie porusza; każda zmiana ląduje od razu",
  "The panel stays docked at any window width":"Panel pozostaje zadokowany przy każdej szerokości okna",
  "The panel hides itself when the window gets narrow":"Panel chowa się, gdy okno staje się wąskie",
  "Every category row stays visible":"Każdy rząd kategorii pozostaje widoczny",
  "The bar keeps two rows, and Ctrl peeks at the others":"Pasek zostaje przy dwóch wierszach, a Ctrl pozwala zerknąć na pozostałe",
  "Click, then press the new key combo":"Kliknij, a następnie naciśnij nową kombinację klawiszy",
  "Press keys…":"Naciśnij klawisze…",
  "Fixed keys":"Klawisze stałe",
  "The grammar the rest stands on: Esc is how key capture itself cancels, arrows and Enter keep their native meanings, and a held Ctrl is a hold, not a chord.":"Gramatyka, na której opiera się reszta: Esc anuluje samo przechwytywanie klawiszy, strzałki i Enter zachowują swoje naturalne znaczenie, a przytrzymany Ctrl to przytrzymanie, nie skrót.",
  "Delete this custom card?\n\nIt disappears from Etiuda and from anything you export. The catalog has no version to restore.":"Usunąć tę własną kartę?\n\nZniknie z Etiudy i ze wszystkiego, co wyeksportujesz. Katalog nie ma jej wersji do przywrócenia.",
  "Delete this card?\n\nIt disappears from Etiuda and from anything you export. Reset restores it from the catalog.":"Usunąć tę kartę?\n\nZniknie z Etiudy i ze wszystkiego, co wyeksportujesz. Przycisk Przywróć odtworzy ją z katalogu.",
  "Delete this custom intent?":"Usunąć tę własną intencję?",
  "Delete this intent?\n\nIt disappears from Etiuda and from anything you export. Reset restores it from the catalog.":"Usunąć tę intencję?\n\nZniknie z Etiudy i ze wszystkiego, co wyeksportujesz. Przycisk Przywróć odtworzy ją z katalogu.",
  "Keep current":"Zachowaj obecny",
  "Start empty":"Zacznij pusto",
  "Load it":"Wczytaj",
  "Load catalog":"Wczytaj katalog",
  "Show all hidden":"Pokaż wszystkie ukryte",
  "English cards - click, or press":"Karty po angielsku - kliknij lub naciśnij",
  "Polish cards - click, or press":"Karty po polsku - kliknij lub naciśnij",
  "toggles":"przełącza",
  "Library":"Biblioteka",
  "Maintenance":"Konserwacja",
  "Import failed -":"Import nie powiódł się -",
  "Moved to":"Przeniesiono do",
  "Restored original -":"Przywrócono oryginał -",
  "Edit, hide or restore every card, intent and category":"Edytuj, ukrywaj i przywracaj karty, intencje i kategorie",
  "Add a category":"Dodaj kategorię",
  "New category":"Nowa kategoria",
  "New category…":"Nowa kategoria…",
  "New category name":"Nazwa nowej kategorii",
  "Create a new category":"Utwórz nową kategorię",
  "Move or delete cards in this category first":"Najpierw przenieś lub usuń karty z tej kategorii",
  "Move or delete the cards in this category first":"Najpierw przenieś lub usuń karty z tej kategorii",
  "Create a card in":"Utwórz kartę w",
  "Delete card":"Usuń kartę",
  "Delete this card":"Usuń tę kartę",
  "New intent":"Nowa intencja",
  "New intent…":"Nowa intencja…",
  "Create a custom intent":"Utwórz własną intencję",
  "Write a new clause for {INTENT}":"Napisz nową klauzulę dla {INTENT}",
  "Delete this intent":"Usuń tę intencję",
  "Export…":"Eksportuj…",
  "No catalogs in {FOLDER} yet. Import one, or drop a file into the folder.":"W {FOLDER} nie ma jeszcze katalogów. Zaimportuj jeden albo wrzuć plik do folderu.",
  "Import catalog…":"Importuj katalog…",
  "Build integrated copy…":"Zbuduj zintegrowaną kopię…",
  "Clear local memory":"Wyczyść pamięć lokalną",
  "Eject catalog":"Odłącz katalog",
  "Previous":"Poprzedni",
  /* Qualified because the tour already owns a plain "Next" and calls it Dalej; Previous has
     no such clash, so it stays plain rather than being qualified for symmetry alone. */
  "editor␟Next":"Następny",
  "Editor: previous":"Edytor: poprzedni",
  "Editor: next":"Edytor: następny",
  "In an editor: open the one before it":"W edytorze: otwiera poprzednią pozycję",
  "In an editor: open the one after it":"W edytorze: otwiera następną pozycję",
  "Editor: previous language":"Edytor: poprzedni język",
  "Editor: next language":"Edytor: następny język",
  "In an editor: the language tab before this one":"W edytorze: poprzedni język",
  "In an editor: the language tab after this one":"W edytorze: następny język",
  "Switch the language being edited":"Przełącz edytowany język",
  "This card has unsaved changes. Leave it without saving?":"Ta karta ma niezapisane zmiany. Opuścić ją bez zapisywania?",
  "Restored your cards and stars from an earlier build.":"Przywrócono Twoje karty i gwiazdki z wcześniejszej wersji.",
  "Your intent edits and stars are set aside: this catalog cannot say which intent each belongs to.":"Odłożono Twoje zmiany i gwiazdki przy intencjach: ten katalog nie wskazuje, której intencji dotyczą.",
  "Forget every personal card, edit, hide, rename and layout choice in this browser; the loaded catalog stays. It is also how you bring back anything you deleted.":"Zapomnij wszystkie własne karty, zmiany, ukrycia, zmiany nazw i ustawienia układu w tej przeglądarce; wczytany katalog zostaje. Tak też przywracasz to, co usunięte.",
  "Put the catalog down and restart empty. Your cards, edits, name, theme and layout all stay.":"Odłóż katalog i uruchom Etiudę pustą. Twoje karty, zmiany, nazwa, motyw i układ zostają.",
  "Eject the catalog from this browser?":"Odłączyć katalog od tej przeglądarki?",
  "Your own cards, edits, stars and card order are KEPT - load this catalog again":"Twoje własne karty, zmiany, gwiazdki i kolejność kart ZOSTAJĄ - wczytaj ten katalog ponownie,",
  "Your own cards, edits, stars and card order are KEPT, and come back where they were when you load this catalog again.":"Twoje własne karty, zmiany, gwiazdki i kolejność kart ZOSTAJĄ i wracają na swoje miejsca, gdy wczytasz ten katalog ponownie.",
  "Loading a different catalog clears them, because they were written against this one.":"Wczytanie innego katalogu je usunie, ponieważ powstały dla tego katalogu.",
  "Your agent name, theme and layout choices stay, and catalog files on disk are not touched.":"Twoja nazwa agenta, motyw i ustawienia układu pozostają, a pliki katalogu na dysku nie są ruszane.",
  "Etiuda restarts empty. If a catalog file sits beside it you will be asked whether to load it.":"Etiuda uruchomi się pusta. Jeśli obok leży plik katalogu, pojawi się pytanie o jego wczytanie.",
  "and forgets your agent name, theme and layout choices.":"i zapomina Twoją nazwę agenta, motyw oraz ustawienia układu.",
  "The loaded catalog stays, and Etiuda restarts with it.":"Wczytany katalog pozostaje, a Etiuda uruchomi się z nim.",
  "Save everything loaded now as a catalog file, your edits merged in":"Zapisz wszystko, co wczytane, jako plik katalogu z Twoimi zmianami",
  "Load a catalog file from disk: it is read as data, never executed. It replaces what is loaded now, and nothing on disk changes.":"Wczytaj plik katalogu z dysku: jest czytany jako dane, nigdy wykonywany. Zastępuje to, co wczytane teraz, a pliki na dysku pozostają bez zmian.",
  "Bake the catalog into one HTML file that needs nothing beside it":"Zapisz katalog w jednym pliku HTML, który nie potrzebuje nic obok",
  "Reset personal data":"Wyczyść dane osobiste",
  "Reset Etiuda":"Zresetuj Etiudę",
  "Edit card":"Edytuj kartę",
  "Edit this intent":"Edytuj tę intencję",
  "hold Ctrl to edit, Shift to hide":"przytrzymaj Ctrl, aby edytować, Shift, aby ukryć",
  "Edit intent":"Edytuj intencję",
  "Edit this category":"Edytuj tę kategorię",
  "Edit this category's names, icon and colour":"Edytuj nazwy, ikonę i kolor tej kategorii",
  "Delete this category. It is empty, so nothing is lost.":"Usuń tę kategorię. Jest pusta, więc nic nie zostanie utracone.",
  "hold Ctrl to edit it":"przytrzymaj Ctrl, aby edytować",
  "Delete category":"Usuń kategorię",
  "Discard your changes and restore the catalog's category.":"Odrzuć swoje zmiany i przywróć kategorię z katalogu.",
  "Nothing to discard - this matches the catalog.":"Nie ma czego odrzucać - to jest zgodne z katalogiem.",
  "This is yours, so the catalog has no version to restore.":"To jest Twoje, więc katalog nie ma wersji do przywrócenia.",
  "Discard your changes to this category?":"Odrzucić swoje zmiany w tej kategorii?",
  "Category reset":"Kategoria przywrócona",
  "Delete this empty category":"Usuń tę pustą kategorię",
  "Edit category":"Edytuj kategorię",
  "Title":"Tytuł",
  "Icon":"Ikona",
  "Colour":"Kolor",
  "Macro":"Makro",
  "Clause":"Fraza",
  "Comment action":"Czynność do komentarza",
  "Clause is required":"Fraza jest wymagana",
  "Category name":"Nazwa kategorii",
  "Name":"Nazwa",
  "Editing":"Edytujesz",
  "Keywords":"S\u0142owa kluczowe",
  "1 word":"1 s\u0142owo",
  "{N} words":"s\u0142\u00f3w: {N}",
  "zmieniono lot":"zmieniono lot",
  /* The three below are example VALUES, not chrome: the field takes English, so its hint
     stays English whatever the interface says. */
  "flight change":"flight change",
  "flight changed":"flight changed",
  "zmiana lotu":"zmiana lotu",
  "what was done":"co zostało zrobione",
  "extra words for search":"dodatkowe słowa do wyszukiwania",
  "a short name you will recognise":"krótka nazwa, którą rozpoznasz",
  "the text the customer receives":"tekst, który otrzyma klient",
  "guidance for you, never sent":"wskazówka dla Ciebie, nigdy nie wysyłana",
  "Note":"Notatka",
  "Blank lines split the text into separately copyable alternatives.":"Puste linie dzielą tekst na osobno kopiowane warianty.",
  "Numbers the alternatives as ordered steps.":"Numeruje warianty jako kolejne kroki.",
  "Rings green under every intent - for text that always applies, like an opener.":"Świeci na zielono przy każdej intencji - dla tekstu, który pasuje zawsze, jak powitanie.",
  "Sorts above the other linked cards when an intent is picked.":"Sortuje się nad pozostałymi powiązanymi kartami, gdy wybrano intencję.",
  "Save changes":"Zapisz zmiany",
  "Discard changes":"Odrzuć zmiany",
  "Close without saving any change":"Zamknij bez zapisywania zmian.",
  "Save this card on this computer":"Zapisz tę kartę na tym komputerze.",
  "Save this intent on this computer":"Zapisz tę intencję na tym komputerze.",
  "Delete this card: a built-in one returns on Reset, one you made does not":"Usuń tę kartę: wbudowana wróci po zresetowaniu, Twoja własna nie",
  "Delete this intent: a built-in one returns on Reset, one you made does not":"Usuń tę intencję: wbudowana wróci po zresetowaniu, Twoja własna nie",
  "Discard your edits and restore the catalog wording.":"Odrzuć swoje zmiany i przywróć treść z katalogu.",
  "Restore built-in quick facts":"Przywróć wbudowane szybkie fakty",
  "Delete this custom card permanently?":"Usunąć tę własną kartę na stałe?",
  "Delete this empty category?\n\nA Reset restores it from the catalog.":"Usunąć tę pustą kategorię?\n\nPrzycisk Przywróć odtworzy ją z katalogu.",
  "Reset all shortcuts to defaults?":"Przywrócić domyślne skróty klawiszowe?",
  "Restore built-in quick facts? Your edited text will be discarded.":"Przywrócić wbudowane szybkie fakty? Twój zmieniony tekst zostanie odrzucony.",
  "{KEY} is fixed and keeps its own meaning":"{KEY} to klawisz stały i zachowuje swoje znaczenie",
  "Saved {KEY}":"Zapisano {KEY}",
  "{N} card":"{N} karta",
  "{N} cards":"{N} kart",
  "few␟{N} cards":"{N} karty",
  "many␟{N} cards":"{N} kart",
  "{N} macro":"{N} makro",
  "{N} macros":"{N} makr",
  "few␟{N} macros":"{N} makra",
  "many␟{N} macros":"{N} makr",
  "{N} intent":"{N} intencja",
  "{N} intents":"{N} intencji",
  "few␟{N} intents":"{N} intencje",
  "many␟{N} intents":"{N} intencji",
  "{N} category":"{N} kategoria",
  "{N} categories":"{N} kategorii",
  "few␟{N} categories":"{N} kategorie",
  "many␟{N} categories":"{N} kategorii",
  "{CARDS} · {MACROS} · {INTENTS} · {CATEGORIES}":"{CARDS} · {MACROS} · {INTENTS} · {CATEGORIES}",
  "{MACROS} in {CARDS}, {CATEGORIES}":"{MACROS}, {CARDS}, {CATEGORIES}",
  "{MACROS} in {CARDS} · {INTENTS} · {CATEGORIES}":"{MACROS} · {CARDS} · {INTENTS} · {CATEGORIES}",
  "Built {FILE} with {MACROS} inside":"Zbudowano {FILE}, w środku {MACROS}",
  "Exported {FILE} with {MACROS} in {CARDS}":"Wyeksportowano {FILE}: {MACROS}, {CARDS}",
  "Card deleted":"Karta usunięta",
  "Custom card deleted":"Własna karta usunięta",
  "Category added":"Kategoria dodana",
  "Category deleted":"Kategoria usunięta",
  "Category updated":"Kategoria zaktualizowana",
  "Intent added to Favourites":"Intencja dodana do Ulubionych",
  "Intent removed from Favourites":"Intencja usunięta z Ulubionych",
  "Intent deleted":"Intencja usunięta",
  "Intent restored to original":"Przywrócono pierwotną intencję",
  "Intent not found":"Nie znaleziono intencji",
  "Intent order reset":"Przywrócono kolejność intencji",
  "Intent panel width reset":"Przywrócono szerokość panelu intencji",
  "Added to Favourites":"Dodano do Ulubionych",
  "Removed from Favourites":"Usunięto z Ulubionych",
  "Shown again":"Pokazano ponownie",
  "Tab cleared":"Rozmowa wyczyszczona",
  "no text yet":"jeszcze bez tekstu",
  "Copy the report: counts and environment only, never your content":"Skopiuj raport: tylko liczby i dane o środowisku, nigdy Twoja treść",
  "All tabs closed":"Zamknięto wszystkie rozmowy",
  "Press Esc again to close all tabs":"Naciśnij Esc ponownie, aby zamknąć wszystkie rozmowy",
  "{INTENT} cleared":"Wyczyszczono {INTENT}",
  "Shortcuts reset":"Przywrócono domyślne skróty",
  "Press the new shortcut (Esc to cancel, Backspace for the default)":"Naciśnij nowy skrót (Esc anuluje, Backspace przywraca domyślny)",
  "Built-in quick facts restored":"Przywrócono wbudowane szybkie fakty",
  "The browser blocked the copy, so select the text yourself.":"Przeglądarka zablokowała kopiowanie, więc zaznacz tekst samodzielnie.",
  "Some required fields are empty":"Niektóre wymagane pola są puste",
  "Title is required":"Tytuł jest wymagany",
  "Macro text is required":"Tekst makra jest wymagany",
  "The catalog is empty, so there is nothing to export.":"Katalog jest pusty, więc nie ma czego wyeksportować.",
  "The catalog is empty, so there is nothing to build.":"Katalog jest pusty, więc nie ma czego zbudować.",
  "Could not read file":"Nie udało się odczytać pliku",
  "Could not read this page's own source":"Nie udało się odczytać źródła tej strony",
  "Could not save, perhaps because the browser's storage is full.":"Nie udało się zapisać, być może pamięć przeglądarki jest zapełniona.",
  "Could not save shortcuts":"Nie udało się zapisać skrótów",
  "Could not save the catalog, perhaps because the browser's storage is full.":"Nie udało się zapisać katalogu, być może pamięć przeglądarki jest zapełniona.",
  "This browser is not storing anything, so a catalog cannot be kept here":"Ta przeglądarka niczego nie zapisuje, więc nie można tu zachować katalogu",
  "Could not find the embedded-catalog slot":"Nie znaleziono miejsca na wbudowany katalog",
  "load a sample catalog":"wczytaj przykładowy katalog",
  "Copy report":"Kopiuj raport",
  "Link copied":"Skopiowano link",
  "Report copied":"Skopiowano raport",
  "Nothing here yet.":"Jeszcze nic tu nie ma.",
  "Empty.":"Pusto.",
  "No categories.":"Brak kategorii.",
  "No intents.":"Brak intencji.",
  "No intents available.":"Brak dostępnych intencji.",
  "Uncategorised":"Bez kategorii",
  "Name this catalog":"Nazwij ten katalog",
  "Name this build":"Nazwij tę kompilację",
  "Edition":"Wydanie",
  "Editions read 2026-09-15, or 2026-09-15a for a second the same day.":"Wydanie ma postać 2026-09-15, a drugie tego samego dnia - 2026-09-15a.",
  "Saves as":"Zapisze się jako",
  "Reset shortcuts":"Przywróć skróty",
  "What Etiuda is, and every keyboard shortcut":"Czym jest Etiuda i wszystkie skróty klawiszowe",
  "Interface language, appearance and keyboard shortcuts":"Język interfejsu, wygląd i skróty klawiszowe",
  "Hide the category bar; hold Ctrl to peek at it while hidden":"Ukryj pasek kategorii; przytrzymaj Ctrl, aby na niego zerknąć",
  "Hide the intent panel; its chips then appear on the first card that uses {INTENT}":"Ukryj panel intencji; jego chipy pojawią się wtedy na pierwszej karcie z {INTENT}",
  "AGENT":"AGENT",
  "PAX":"PAX",
  "INTENT":"INTENCJA",
  "search intents and cards":"szukaj intencji i kart",
  "Search":"Szukaj",
  "One search: intents rank in the panel, cards filter below":"Jedno wyszukiwanie: intencje układają się w panelu, karty filtrują się poniżej",
  "search intents and cards · <kbd>Enter</kbd> selects the marked intent · <kbd>Ctrl</kbd>+<kbd>Enter</kbd> for several":"szukaj intencji i kart · <kbd>Enter</kbd> wybiera zaznaczoną intencję · <kbd>Ctrl</kbd>+<kbd>Enter</kbd> wybiera kilka",
  "Search cleared":"Wyszukiwanie wyczyszczone",
  "Typing in SEARCH ranks intents and filters cards together (both languages).":"Pisanie w SZUKAJ układa intencje i filtruje karty jednocześnie (oba języki).",
  "One box for everything: typing ranks the intents in the panel and filters the cards below it, in both languages. <kbd>↓</kbd> <kbd>↑</kbd> walk the intents that match, skipping the ones already picked; <kbd>Shift</kbd>+<kbd>↑</kbd> jumps to the top of the list, and a second one crosses to the first card (<kbd>Shift</kbd>+<kbd>↓</kbd> works the same way down). <kbd>Enter</kbd> picks the marked intent: it fills <span class=\"fillmiss\">INTENT</span> and rings the linked cards <b class=\"t-go\">green</b>; <kbd>Ctrl</kbd>+<kbd>Enter</kbd> picks and keeps the box for the next one. <kbd>←</kbd> <kbd>→</kbd> step through the categories even from inside the box, and <kbd>Esc</kbd> clears.":"Jedno pole na wszystko: pisanie układa intencje w panelu i filtruje karty poniżej, w obu językach. <kbd>↓</kbd> <kbd>↑</kbd> przechodzą po pasujących intencjach, omijając już wybrane; <kbd>Shift</kbd>+<kbd>↑</kbd> skacze na początek listy, a drugi raz - na pierwszą kartę (<kbd>Shift</kbd>+<kbd>↓</kbd> działa tak samo w dół). <kbd>Enter</kbd> wybiera zaznaczoną intencję - wypełnia <span class=\"fillmiss\">INTENT</span> i obwodzi powiązane karty na <b class=\"t-go\">zielono</b>; <kbd>Ctrl</kbd>+<kbd>Enter</kbd> wybiera i zostawia pole na kolejną. <kbd>←</kbd> <kbd>→</kbd> przechodzą między kategoriami nawet z wnętrza pola, a <kbd>Esc</kbd> czyści.",

  "ROLE":"ROLA",
  "EN":"EN",
  "PL":"PL",
  "Etiuda":"Etiuda",
  "Etiuda catalog":"Katalog Etiudy",
  "A macro bank for live chat":"Bank makr do czatu na żywo",
  "Menu":"Menu",
  "Cards, the intent panel and the category bar":"Karty, panel intencji i pasek kategorii",
  "More tools":"Więcej narzędzi",
  "The tools this window is too narrow to show":"Narzędzia, na które to okno jest za wąskie",
  "Quick facts":"Szybkie fakty",
  "Fees, deadlines and limits":"Opłaty, terminy i limity",
  "Switch between the light and dark themes":"Przełącz między motywem jasnym a ciemnym",
  "Switch card language":"Przełącz język kart",
  "The language the macros are shown in, kept per tab":"Język, w którym pokazywane są makra, osobno dla każdej rozmowy",
  "Show English cards":"Pokaż karty po angielsku",
  "Show Polish cards":"Pokaż karty po polsku",
  "Scroll tabs left":"Przewiń rozmowy w lewo",
  "Scroll tabs right":"Przewiń rozmowy w prawo",
  "The new tab starts with cleared fields and your settings kept.":"Nowa rozmowa ma puste pola i zachowane ustawienia.",
  "New tab (same shared settings; cleared PAX, intent, ROLE, categories)":"Nowa rozmowa (te same wspólne ustawienia; wyczyszczone PAX, intencja, ROLE, kategorie)",
  "One tab per chat, each with its own PAX, intent, ROLE and categories":"Jedna rozmowa na czat, każda z własnym PAX, intencją, ROLE i kategoriami",
  "Click to switch, or drag to reorder":"Kliknij, aby przełączyć, lub przeciągnij, aby zmienić kolejność",
  "The name customers see, and the language Etiuda's own buttons and menus are written in":"Nazwa, którą widzą klienci, i język przycisków oraz menu samej Etiudy",
  "The customer's name as the chat gives it, filling {PAX} with the tidied first name":"Imię i nazwisko klienta w postaci z czatu, wypełnia {PAX} uporządkowanym imieniem",
  "{PAX} fills the first name even when the chat gives the full name.":"{PAX} wstawia samo imię, nawet gdy z czatu przychodzi imię i nazwisko.",
  "class":"klasa",
  "Who is on the chat, filling {ROLE} in internal comments":"Kto jest po drugiej stronie, wypełnia {ROLE} w komentarzach wewnętrznych",
  "booker, customer, account holder":"rezerwujący, klient, właściciel konta - wypełniają {ROLE} w komentarzach wewnętrznych",
  "Notches for the ROLE wheel, comma-separated; blanks and repeats are dropped":"Pozycje pokrętła ROLE po przecinku; puste i powtórzone są pomijane",
  "Intent list":"Lista intencji",
  "Click to pick, again to clear, and hold Ctrl for several":"Kliknij, aby wybrać, ponownie, aby wyczyścić, a Ctrl wybiera kilka",
  "Clear":"Wyczyść",
  "Clear PAX":"Wyczyść PAX",
  "Clear agent":"Wyczyść agenta",
  "Clear agent name":"Wyczyść imię agenta",
  "Clear customer name":"Wyczyść imię klienta",
  "Clear intents":"Wyczyść intencje",
  "Clear all selected intents":"Wyczyść wszystkie wybrane intencje",
  "All categories":"Wszystkie kategorie",
  "Pick a category":"Wybierz kategorię",
  "Show all categories; double-click to reset their order":"Pokaż wszystkie kategorie; kliknij dwukrotnie, aby przywrócić ich kolejność",
  "Filter by category; a green ring marks one that relates to the chosen intent":"Filtruj po kategoriach; zielona obwódka oznacza kategorię powiązaną z wybraną intencją",
  "Filter by category; a green ring marks one that relates to the chosen intent, and {KEY} shows every row":"Filtruj po kategoriach; zielona obwódka oznacza kategorię powiązaną z wybraną intencją, a {KEY} pokazuje wszystkie wiersze",
  "Supporting category":"Kategoria pomocnicza",
  "Linked to the selected intent":"Powiązana z wybraną intencją",
  "Hover here or hold Ctrl to show the intent panel":"Najedź tutaj lub przytrzymaj Ctrl, aby pokazać panel intencji",
  "Keep the panel docked even on a narrow window":"Utrzymuje panel zadokowany nawet przy wąskim oknie",
  "Lock the intent panel open":"Zablokuj panel intencji",
  "Double-click to reset the intent order":"Kliknij dwukrotnie, aby przywrócić kolejność intencji",
  "Drag to reorder":"Przeciągnij, aby zmienić kolejność",
  "Drag to reorder, or onto a category to move it there":"Przeciągnij, aby zmienić kolejność, albo na kategorię, aby ją tam przenieść",
  "Click to copy":"Kliknij, aby skopiować",
  "Click to copy full URL":"Kliknij, aby skopiować pełny adres",
  "Click to copy, or drag to reorder these":"Kliknij, aby skopiować, lub przeciągnij, aby zmienić kolejność",
  "Hide this card":"Ukryj tę kartę",

  "Show this card again":"Pokaż tę kartę ponownie",
  "Hide this intent":"Ukryj tę intencję",
  "Hide this intent: it greys out and drops to the bottom":"Ukryj tę intencję: zszarzeje i spadnie na koniec listy",
  "Show this intent again":"Pokaż tę intencję ponownie",
  "In Favourites":"W Ulubionych",
  "Edit this card":"Edytuj tę kartę",
  "Open the full editor":"Otwórz pełny edytor",
  "Edit quick facts":"Edytuj szybkie fakty",
  "Edit quick facts text":"Edytuj treść szybkich faktów",
  "Close this screen":"Zamknij ten ekran",
  "Dismiss":"Zamknij",
  "Back":"Wstecz",
  "Next":"Dalej",
  "Done":"Gotowe",
  "Save":"Zapisz",
  "Cancel":"Anuluj",
  "Delete":"Usuń",
  "Reset":"Przywróć",
  "Export":"Eksportuj",
  "Not now":"Nie teraz",
  "Welcome":"Witaj",
  "New here?":"Pierwszy raz tutaj?",
  "Skip tour":"Pomiń przewodnik",
  "Show tour":"Pokaż przewodnik",
  "Press Esc to leave the tour.":"Naciśnij Esc, aby wyjść z przewodnika.",
  "A guided walk through the main controls":"Przewodnik po głównych elementach",
  "Library…":"Biblioteka…",
  "Settings…":"Ustawienia…",
  "Show tour…":"Pokaż przewodnik…",
  "About Etiuda":"O Etiudzie",
  "Hide intent panel":"Ukryj panel intencji",
  "Show intent panel":"Pokaż panel intencji",
  "Lock intent panel":"Zablokuj panel intencji",
  "Unlock intent panel":"Odblokuj panel intencji",
  "Hide categories":"Ukryj kategorie",
  "Show categories":"Pokaż kategorie",
  "Lock categories":"Zablokuj kategorie",
  "Unlock categories":"Odblokuj kategorie",
  "Settings":"Ustawienia",
  "The language of the buttons and menus, not of the macros: those follow EN|PL in the header":"Język przycisków i menu, nie makr: te idą za przełącznikiem EN|PL w nagłówku",
  "Appearance":"Wygląd",
  "Theme":"Motyw",
  "Light":"Jasny",
  "Dark":"Ciemny",
  "System":"Systemowy",
  "System follows your computer's own setting.":"Systemowy podąża za ustawieniem Twojego komputera.",
  "Blur effects":"Efekty rozmycia",
  "Blurred panel backgrounds and the blur behind dialogs. Turn off if text reads less clearly, or the machine struggles.":"Rozmyte tło paneli i rozmycie za oknami dialogowymi. Wyłącz, jeśli tekst jest mniej czytelny albo komputer zwalnia.",
  "Animations":"Animacje",
  "Transitions, slides, and the cards re-sorting themselves. Switches itself off when your system asks for reduced motion.":"Przejścia, przesunięcia i samo przestawianie się kart. Wyłącza się samo, gdy system prosi o ograniczenie ruchu.",
  "Keyboard shortcuts":"Skróty klawiszowe",
  "An alternative: click, then press the key combo":"Skrót alternatywny: kliknij, a następnie naciśnij kombinację klawiszy",
  "Press the alternative (Esc to cancel, Backspace to clear)":"Naciśnij skrót alternatywny (Esc anuluje, Backspace usuwa)",
  "Alternative cleared":"Skrót alternatywny usunięty",
  "Back to the default":"Przywrócono domyślny skrót",
  "Reset defaults":"Przywróć domyślne",
  "Layout":"Układ",
  "Lock the intent panel":"Zablokuj panel intencji",
  "Keep it docked even when the window is narrow, instead of letting it hide itself.":"Panel zostaje zadokowany także przy wąskim oknie, zamiast chować się sam.",
  "Lock the category bar":"Zablokuj pasek kategorii",
  "Keep every category row visible, instead of collapsing to two lines.":"Wszystkie rzędy kategorii pozostają widoczne, zamiast zwijać się do dwóch linii.",
  "On":"Wł.",
  "Off":"Wył.",
  "Close":"Zamknij",
  "Minimise":"Minimalizuj",
  "Maximise":"Maksymalizuj",
  "Restore":"Przywróć",
  "Interface language":"Język interfejsu",
  "Theme follows the system":"Motyw podąża za systemem",
  "Animations reduced":"Animacje ograniczone",
  "Animations on":"Animacje włączone",
  "Blur effects on":"Efekty rozmycia włączone",
  "Blur effects off":"Efekty rozmycia wyłączone"
};
// Is this a language this build carries? The table itself stays private to this file.
function uiLangKnown(l){ return !!(l && UI_STRINGS[l]); }
function uiLang(){
  const l=lsGet("eUiLang");
  return (l && UI_STRINGS[l]) ? l : "en";       // an unknown or retired code reads English
}
/** English is the source text, so it IS the fallback - a missing key reads English, never
 *  blank and never the key name. That rule is what lets a language ship half-translated: the
 *  gaps read English rather than breaking, so a new language can land a section at a time. */
/* KEYED BY THE ENGLISH SOURCE, not symbolic names: the fallback IS the key, so a miss
   cannot render blank or leak "menu.library" to a passenger, and adding a language is
   filling in a column. The cost - editing English orphans its translation - is exactly
   what i18n-scan.js reports, loudly rather than silently. */
function t(en){
  const tab=UI_STRINGS[uiLang()];
  return (tab && tab[en]!=null) ? tab[en] : en;
}
// Every question the app asks is asked in the interface language, so it asks through t().
function ask(m){ return confirm(t(m)); }
let tt;
const TOAST_MS=1700;
var toastSerial=0;
function toast(m){
  toastSerial++;
  /* Every message the app speaks passes through here, so this is the one place a toast needs
     translating - not fifty call sites. */
  m=t(m);
  const el=$("#toast"); el.textContent=m; markCut(el); el.classList.add("show");
  clearTimeout(tt); tt=setTimeout(()=>el.classList.remove("show"),TOAST_MS);
}
/* TRANSLATE AT THE SINKS, not at 200 call sites: an attribute in markup, a chrome
   element's text, or a toast. SCOPED TO CHROME - the card list, the panel's rows and the
   facts panel hold CATALOG content, the customer's, never touched by a UI language; that
   is also why nothing here walks `document`. */
/* ONE ENGLISH WORD, TWO MEANINGS ("name": a person's in the header, a catalog's in
   maintenance). tc() tries a context-qualified key first, falls back to the plain one - a
   language pays nothing until it needs it. The separator is U+241F, which cannot occur in
   UI text, so a context key can never collide with a real one. */
const T_CTX="\u241f";
function tc(ctx,en){
  const tab=UI_STRINGS[uiLang()];
  if(tab){ const v=tab[ctx+T_CTX+en]; if(v!=null) return v; }
  return t(en);
}
/* POLISH COUNTS A NOUN THREE WAYS where English counts two: 1 karta, 2 karty, 5 kart, with the
   teens taking the last of those. The two plural forms are context keys on the plural, so a
   language holding one plural answers the same call with one string.
   EVERY NOUN KEY BELOW CARRIES A NON-BREAKING SPACE, invisible here: a count must not be left
   at the end of a line with its noun starting the next. */
function counted(n,one,many){
  if(n===1) return t(one).replace("{N}",n);
  const ten=n%10, hundred=n%100;
  const few = ten>=2 && ten<=4 && !(hundred>=12 && hundred<=14);
  return tc(few?"few":"many", many).replace("{N}",n);
}
/* ONE PLACE HOLDS THE NOUNS, and each screen brings its own key holding only their order and
   what sits between them - which is how a language that would not order them this way, or would
   not use the same preposition, says so. A count of nothing simply leaves its slot unmentioned. */
function catalogCountsLine(key,cardN,macroN,intentN,catN){
  return t(key)
    .replace("{CARDS}",counted(cardN,"{N} card","{N} cards"))
    .replace("{MACROS}",counted(macroN,"{N} macro","{N} macros"))
    .replace("{INTENTS}",counted(intentN,"{N} intent","{N} intents"))
    .replace("{CATEGORIES}",counted(catN,"{N} category","{N} categories"));
}
/* A FILE'S OWN DATE AND TIME, formatted explicitly rather than by locale: toLocaleDateString
   follows the machine rather than the interface language, so one file would read two ways on two
   desks. Day first, both parts padded, and the time as well as the date because two catalogs
   saved on the same day are told apart by nothing else. Empty for a file with no time. */
function fileStamp(ms){
  const n=+ms||0;
  if(!n) return "";
  const d=new Date(n), p=v=>String(v).padStart(2,"0");
  return p(d.getDate())+"."+p(d.getMonth()+1)+"."+d.getFullYear()+" "+p(d.getHours())+":"+p(d.getMinutes());
}
const I18N_ATTRS=["title","aria-label","placeholder"];
/* data-i18n-skip marks CATALOG text - an intent clause, a card title, a category name.
   The sweep neither translates nor descends into them, which lets it cover regions mixing
   engine words with the employer's; without it an intent named exactly like a UI string
   would be silently rewritten. */
function translateTree(root){
  /* NOT "return early on English". Every node this touched remembers its English source, and
     t() on English hands that source straight back - so running the sweep is exactly how the
     English is put back. Returning early meant a language could be entered and never left. */
  if(!root) return;
  const els=root.querySelectorAll ? root.querySelectorAll("*") : [];
  const all=root.nodeType===1 ? [root].concat(Array.prototype.slice.call(els)) : Array.prototype.slice.call(els);
  all.forEach(el=>{
    if(el.closest && el.closest("[data-i18n-skip]")) return;
    I18N_ATTRS.forEach(a=>{
      const v=el.getAttribute && el.getAttribute(a);
      if(!v) return;
      /* The ORIGINAL English is remembered on the element, so switching back - or switching to a
         third language - translates from the source rather than from the last translation. */
      const src=el.getAttribute("data-i18n-"+a) || v;
      const out=t(src);
      if(out!==v){ el.setAttribute("data-i18n-"+a, src); el.setAttribute(a, out); }
    });
    /* Text only where the element holds nothing but text: a button, a label, a heading. Anything
       with element children is left alone, because replacing its text would delete them. */
    if(el.children && el.children.length===0 && el.textContent && el.textContent.trim()){
      const src=el.getAttribute("data-i18n-text") || el.textContent.trim();
      const out=t(src);
      if(out!==el.textContent.trim()){ el.setAttribute("data-i18n-text", src); el.textContent=out; }
    }
    /* An element WITH children still has text of its own between them - halves a leaf rule
       can never reach - so each direct text node is swapped in place, the elements left
       where they were. A text node cannot carry an attribute, so it remembers its own
       original on itself. */
    else if(el.childNodes){
      Array.prototype.forEach.call(el.childNodes, n=>{
        if(n.nodeType!==3 || !n.nodeValue || !n.nodeValue.trim()) return;
        const raw=n.nodeValue, txt=raw.trim();
        const src=n.eI18nSrc || txt;
        const out=t(src);
        if(out!==txt){ n.eI18nSrc=src; n.nodeValue=raw.replace(txt, out); }
      });
    }
  });
}
/** The app's own furniture, never the catalog's content. */
function translateChrome(){
  /* #intentRail carries the engine's own labels AND the catalog's intent clauses; the
     clauses are marked data-i18n-skip where they are written, so the sweep is safe here. */
  ["header","#settingsMenu","#modalCard","footer","#tourRoot",
   "#intentRail","#tourInvite","#sampleMark"].forEach(sel=>{
    const el=document.querySelector(sel);
    if(el) translateTree(el);
  });
}

export {
  UI_LANGS,
  uiLangKnown,
  uiLang,
  t,
  ask,
  tc,
  counted,
  catalogCountsLine,
  fileStamp,
  translateTree,
  translateChrome,
  toast,
  TOAST_MS,
  toastSerial
};
