/* The module tree's entry, and the bridge to what is not extracted yet.
   src/monolith.js is still one classic script sharing the artifact's global scope, and it binds
   these names by name. A top-level function or const in a classic script is already a property
   of the global object, so handing them over this way gives the monolith the binding kind those
   names had. A line goes with every module; the file goes when the monolith does. */
import * as icons from "./modules/icons.js";
import * as stock from "./modules/stock.js";
import * as polish from "./modules/polish.js";
import * as contentModel from "./modules/content-model.js";
import * as words from "./modules/words.js";
import * as greeting from "./modules/greeting.js";
import * as cardFields from "./modules/card-fields.js";
import * as catRoles from "./modules/cat-roles.js";
import * as env from "./modules/env.js";
import * as cardModel from "./modules/card-model.js";
import * as cardBlocks from "./modules/card-blocks.js";
import * as storage from "./modules/storage.js";
import * as columns from "./modules/columns.js";
import * as spell from "./modules/spell.js";
import * as scoring from "./modules/scoring.js";
import * as affinity from "./modules/affinity.js";
import * as intentText from "./modules/intent-text.js";
import * as maintenance from "./modules/maintenance.js";
import * as shortcuts from "./modules/shortcuts.js";
import * as cardOrder from "./modules/card-order.js";
import * as catalog from "./modules/catalog.js";
import * as collapse from "./modules/collapse.js";
import * as tour from "./modules/tour.js";
import * as editors from "./modules/editors.js";
import * as catalogFile from "./modules/catalog-file.js";
import * as langTabs from "./modules/lang-tabs.js";
import * as cardEditor from "./modules/card-editor.js";
import * as macrosJson from "./modules/macros-json.js";
import * as tabs from "./modules/tabs.js";
import * as motion from "./modules/motion.js";
import * as manage from "./modules/manage.js";
import * as settings from "./modules/settings.js";
import * as cardSearch from "./modules/card-search.js";
import * as listPointer from "./modules/list-pointer.js";
import * as facts from "./modules/facts.js";
import * as uiLang from "./modules/ui-lang.js";
import * as railList from "./modules/rail-list.js";
import * as personalPack from "./modules/pack.js";
import * as shed from "./modules/shed.js";
import * as favourites from "./modules/favourites.js";
import * as railPanel from "./modules/rail-panel.js";
import * as paint from "./modules/paint.js";
import * as dialog from "./modules/dialog.js";
import * as headerMenus from "./modules/header-menus.js";
import * as cardScore from "./modules/card-score.js";
import * as searchBox from "./modules/search-box.js";
import * as keydown from "./modules/keydown.js";
import * as catalogOffer from "./modules/catalog-offer.js";
import * as pops from "./modules/pops.js";
import * as recency from "./modules/recency.js";
import * as onOpen from "./modules/on-open.js";
import * as localMemory from "./modules/local-memory.js";
import * as shortcutsList from "./modules/shortcuts-list.js";
import * as pillState from "./modules/pill-state.js";
import * as catIdentity from "./modules/cat-identity.js";
import * as catRelevance from "./modules/cat-relevance.js";
import * as about from "./modules/about.js";
import * as pillNavPeek from "./modules/pill-nav-peek.js";
import * as cardIntent from "./modules/card-intent.js";
import * as pageScroll from "./modules/page-scroll.js";
import * as entryWalk from "./modules/entry-walk.js";
import * as intentId from "./modules/intent-id.js";
import * as cssEsc from "./modules/css-esc.js";
import * as cutText from "./modules/cut-text.js";
import * as pillWalk from "./modules/pill-walk.js";
import * as catalogBoot from "./modules/catalog-boot.js";
import * as catSet from "./modules/cat-set.js";
import * as esc from "./modules/esc.js";
import * as copyEntry from "./modules/copy-entry.js";
import * as cardNode from "./modules/card-node.js";
import * as intentClear from "./modules/intent-clear.js";
import * as escapeLadder from "./modules/escape-ladder.js";
import * as cardBody from "./modules/card-body.js";
import * as pool from "./modules/card-pool.js";
import * as roleDrum from "./modules/role-drum.js";
import * as roleTurn from "./modules/role-turn.js";
import * as fieldClear from "./modules/field-clear.js";
import * as dom from "./modules/dom.js";
import * as theme from "./modules/theme.js";
import * as cardCounts from "./modules/card-counts.js";
import * as rebuild from "./modules/rebuild.js";
import * as render from "./modules/render.js";
import * as mark from "./modules/mark.js";
import * as intentPick from "./modules/intent-pick.js";
import * as notePane from "./modules/note-pane.js";
import * as pillsBar from "./modules/pills-bar.js";
import * as langSeg from "./modules/lang-seg.js";
import * as repaint from "./modules/repaint.js";
import * as pillsBox from "./modules/pills-box.js";
import * as agent from "./modules/agent.js";
import * as ids from "./modules/ids.js";
import * as browserSuggest from "./modules/browser-suggest.js";
import * as runShortcut from "./modules/run-shortcut.js";
Object.assign(globalThis, icons, stock, polish, contentModel, words, greeting, cardFields, catRoles, env, cardModel, cardBlocks, storage, columns, spell, scoring, affinity, intentText, maintenance, shortcuts, cardOrder, catalog, collapse, tour, editors, catalogFile, langTabs, cardEditor, macrosJson, tabs, motion, manage, settings, cardSearch, listPointer, facts, uiLang, railList, personalPack, shed, favourites, railPanel, paint, dialog, headerMenus, cardScore, searchBox, keydown, catalogOffer, pops, recency, onOpen, localMemory, shortcutsList, pillState, catIdentity, catRelevance, about, pillNavPeek, cardIntent, pageScroll, entryWalk, intentId, cssEsc, pillWalk, catalogBoot, catSet, esc, copyEntry, cardNode, intentClear, escapeLadder, cardBody, pool, roleDrum, roleTurn, fieldClear, cutText, dom, theme, cardCounts, rebuild, render, mark, intentPick, notePane, pillsBar, langSeg, repaint, pillsBox, agent, ids, browserSuggest, runShortcut);

/* These are replaced wholesale rather than filled in place, so the monolith has to read the
   binding rather than the copy taken above, before any catalog existed. A name mutated in place
   needs no line here; a name its own module assigns to does. */
// The handles grabDom() fills at boot: the copy spread above is taken while every one is null.
Object.defineProperty(globalThis, "list", { get: () => dom.list });
Object.defineProperty(globalThis, "pax", { get: () => dom.pax });
Object.defineProperty(globalThis, "intentEl", { get: () => dom.intentEl });
Object.defineProperty(globalThis, "agentEl", { get: () => dom.agentEl });
Object.defineProperty(globalThis, "roleSel", { get: () => dom.roleSel });
Object.defineProperty(globalThis, "seg", { get: () => dom.seg });
Object.defineProperty(globalThis, "pills", { get: () => dom.pills });
Object.defineProperty(globalThis, "cardTpl", { get: () => dom.cardTpl });
Object.defineProperty(globalThis, "modalEl", { get: () => dom.modalEl });
Object.defineProperty(globalThis, "modalCard", { get: () => dom.modalCard });
Object.defineProperty(globalThis, "cutRange", { get: () => dom.cutRange });
Object.defineProperty(globalThis, "cutInk", { get: () => dom.cutInk });
Object.defineProperty(globalThis, "CAT_ICONS_CATALOG", { get: () => icons.CAT_ICONS_CATALOG });
Object.defineProperty(globalThis, "CAT_COLORS_CATALOG", { get: () => icons.CAT_COLORS_CATALOG });
Object.defineProperty(globalThis, "CAT_LABELS_PL", { get: () => icons.CAT_LABELS_PL });
Object.defineProperty(globalThis, "FACTS", { get: () => stock.FACTS });
Object.defineProperty(globalThis, "WHO_BASE", { get: () => stock.WHO_BASE });
Object.defineProperty(globalThis, "CATALOG_ROLES", { get: () => catRoles.CATALOG_ROLES });
Object.defineProperty(globalThis, "ALWAYS_CATS", { get: () => catRoles.ALWAYS_CATS });
Object.defineProperty(globalThis, "colLastN", { get: () => columns.colLastN });
Object.defineProperty(globalThis, "colAvailW", { get: () => columns.colAvailW });
Object.defineProperty(globalThis, "eSpellFix", { get: () => spell.eSpellFix });
Object.defineProperty(globalThis, "toastSerial", { get: () => uiLang.toastSerial });
Object.defineProperty(globalThis, "scReady", { get: () => shortcuts.scReady });
Object.defineProperty(globalThis, "scMap", { get: () => shortcuts.scMap });
Object.defineProperty(globalThis, "scMap2", { get: () => shortcuts.scMap2 });
Object.defineProperty(globalThis, "scCaptureId", { get: () => shortcutsList.scCaptureId });
Object.defineProperty(globalThis, "scCaptureSlot", { get: () => shortcutsList.scCaptureSlot });
Object.defineProperty(globalThis, "scRepaint", { get: () => shortcutsList.scRepaint });
Object.defineProperty(globalThis, "E_CATALOG_NAME", { get: () => catalog.E_CATALOG_NAME });
Object.defineProperty(globalThis, "E_CATALOG_VERSION", { get: () => catalog.E_CATALOG_VERSION });
Object.defineProperty(globalThis, "tabs", { get: () => tabs.tabs });
Object.defineProperty(globalThis, "tabSaveTimer", { get: () => tabs.tabSaveTimer });
Object.defineProperty(globalThis, "tabInsertAnimating", { get: () => tabs.tabInsertAnimating });
Object.defineProperty(globalThis, "cardDrag", { get: () => listPointer.cardDrag });
Object.defineProperty(globalThis, "pack", { get: () => personalPack.pack });
Object.defineProperty(globalThis, "BASE_M", { get: () => personalPack.BASE_M });
Object.defineProperty(globalThis, "shedHeld", { get: () => shed.shedHeld });
Object.defineProperty(globalThis, "eShedNat", { get: () => shed.eShedNat });
Object.defineProperty(globalThis, "RAIL_DOCK_MIN", { get: () => railPanel.RAIL_DOCK_MIN });
// Filled in place and never replaced. The line reads as redundant and is not: the bridge
// gate counts the write inside snapshotBaseIntents and requires it.
Object.defineProperty(globalThis, "counts", { get: () => cardCounts.counts });
Object.defineProperty(globalThis, "cardCounts", { get: () => cardCounts.cardCounts });
Object.defineProperty(globalThis, "ePackEpoch", { get: () => personalPack.ePackEpoch });
Object.defineProperty(globalThis, "dragState", { get: () => pillsBar.dragState });
Object.defineProperty(globalThis, "suppressClick", { get: () => pillsBar.suppressClick });
Object.defineProperty(globalThis, "swapLock", { get: () => pillsBar.swapLock });
Object.defineProperty(globalThis, "BASE_STORE", { get: () => intentId.BASE_STORE });
Object.defineProperty(globalThis, "BASE_N", { get: () => intentId.BASE_N });
Object.defineProperty(globalThis, "intentOrder", { get: () => intentId.intentOrder });
Object.defineProperty(globalThis, "intentOrderLoaded", { get: () => intentId.intentOrderLoaded });
